"""Migration D1 aditiva, explícita e reversível.

Este módulo não é executado no startup. A aplicação deve ocorrer somente pelo
executor de schema deployment após preflight e aprovação operacional.
"""

from sqlalchemy import text

VERSION = "fc3_d1_session_instance_20261002"

CREATE_SQL = (
    """
    CREATE TABLE authenticated_session_instance (
        id VARCHAR(36) PRIMARY KEY,
        clinica_id INTEGER NOT NULL REFERENCES clinicas(id),
        usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        invalidated_at TIMESTAMPTZ NULL,
        status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
    );
    CREATE INDEX ix_authenticated_session_instance_clinica_id
        ON authenticated_session_instance (clinica_id);
    CREATE INDEX ix_authenticated_session_instance_usuario_id
        ON authenticated_session_instance (usuario_id);
    CREATE INDEX ix_authenticated_session_instance_status
        ON authenticated_session_instance (status);
    CREATE INDEX ix_authenticated_session_instance_last_seen_at
        ON authenticated_session_instance (last_seen_at);
    """,
    """
    CREATE TABLE clinical_patient_lease (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        clinica_id INTEGER NOT NULL REFERENCES clinicas(id),
        paciente_id INTEGER NOT NULL REFERENCES pacientes(id),
        owner_usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
        owner_session_instance_id VARCHAR(36) NOT NULL REFERENCES authenticated_session_instance(id),
        acquired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        last_heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        expires_at TIMESTAMPTZ NOT NULL,
        lease_token VARCHAR(128) NOT NULL UNIQUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_clinical_patient_lease_clinica_paciente UNIQUE (clinica_id, paciente_id)
    );
    CREATE INDEX ix_clinical_patient_lease_clinica_expires
        ON clinical_patient_lease (clinica_id, expires_at);
    CREATE INDEX ix_clinical_patient_lease_instance_expires
        ON clinical_patient_lease (owner_session_instance_id, expires_at);
    """,
)


def preflight(conn) -> dict:
    names = set(conn.execute(text("SELECT tablename FROM pg_tables WHERE schemaname = current_schema()")).scalars())
    return {
        "database": conn.execute(text("SELECT current_database()")).scalar(),
        "server_version": conn.execute(text("SHOW server_version")).scalar(),
        "tables_absent": not ({"authenticated_session_instance", "clinical_patient_lease"} & names),
        "foreign_tables_present": {"clinicas", "usuarios", "pacientes"}.issubset(names),
    }


def apply(conn) -> None:
    for statement in CREATE_SQL:
        conn.execute(text(statement))


def rollback(conn) -> None:
    conn.execute(text("DROP TABLE IF EXISTS clinical_patient_lease"))
    conn.execute(text("DROP TABLE IF EXISTS authenticated_session_instance"))
