"""Aditive local migration for Google Calendar event mappings.

This script is intentionally not executed automatically. Run only against an
explicitly approved database target.
"""
from sqlalchemy import text

from database import engine


UPGRADE_SQL = """
CREATE TABLE IF NOT EXISTS google_calendar_event_mapping (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinica_id INTEGER NOT NULL REFERENCES clinicas(id) ON DELETE CASCADE,
    google_account_sub VARCHAR(255) NOT NULL,
    calendar_id VARCHAR(255) NOT NULL,
    agenda_id INTEGER NOT NULL,
    google_event_id VARCHAR(255) NOT NULL,
    last_sync_at TIMESTAMPTZ NULL,
    sync_status VARCHAR(20) NOT NULL DEFAULT 'synced',
    last_error VARCHAR(2000) NULL,
    CONSTRAINT ck_google_calendar_mapping_sync_status
      CHECK (sync_status IN ('synced', 'deleted', 'error')),
    CONSTRAINT uq_google_calendar_mapping_destination
      UNIQUE (clinica_id, google_account_sub, calendar_id, agenda_id)
);
CREATE INDEX IF NOT EXISTS ix_google_calendar_mapping_clinica ON google_calendar_event_mapping (clinica_id);
CREATE INDEX IF NOT EXISTS ix_google_calendar_mapping_agenda ON google_calendar_event_mapping (agenda_id);
CREATE INDEX IF NOT EXISTS ix_google_calendar_mapping_event ON google_calendar_event_mapping (google_event_id);
CREATE INDEX IF NOT EXISTS ix_google_calendar_mapping_destination_event
  ON google_calendar_event_mapping (google_account_sub, calendar_id, google_event_id);
CREATE INDEX IF NOT EXISTS ix_google_calendar_mapping_status ON google_calendar_event_mapping (sync_status);
"""

DOWNGRADE_SQL = "DROP TABLE IF EXISTS google_calendar_event_mapping;"


def upgrade() -> None:
    with engine.begin() as connection:
        for statement in UPGRADE_SQL.split(";"):
            if statement.strip():
                connection.execute(text(statement))


def downgrade() -> None:
    with engine.begin() as connection:
        connection.execute(text(DOWNGRADE_SQL))


if __name__ == "__main__":
    upgrade()
