"""Cria/remove a fundação persistente do Histórico de pacientes.

Uso:
    python backend/scripts/migrar_historico_paciente.py
    python backend/scripts/migrar_historico_paciente.py --downgrade

Não importa dados do EasyDental.
"""

import argparse
import sys
from pathlib import Path

from sqlalchemy import text

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from database import engine  # noqa: E402


def upgrade() -> None:
    with engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS historico_paciente (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                clinica_id INTEGER NOT NULL REFERENCES clinicas(id),
                paciente_id INTEGER NOT NULL REFERENCES pacientes(id),
                prestador_id INTEGER NOT NULL REFERENCES prestador_odonto(id),
                source_id INTEGER,
                source_intervencao_id INTEGER,
                data DATE NOT NULL,
                regiao VARCHAR(80),
                descricao TEXT NOT NULL,
                cor INTEGER NOT NULL DEFAULT 16777215,
                criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                atualizado_em TIMESTAMP WITH TIME ZONE,
                criado_por_id INTEGER NOT NULL REFERENCES usuarios(id),
                atualizado_por_id INTEGER REFERENCES usuarios(id),
                CONSTRAINT uq_historico_paciente_clinica_source UNIQUE (clinica_id, source_id)
            )
        """))
        for statement in (
            "CREATE INDEX IF NOT EXISTS ix_historico_paciente_clinica ON historico_paciente (clinica_id)",
            "CREATE INDEX IF NOT EXISTS ix_historico_paciente_paciente ON historico_paciente (paciente_id)",
            "CREATE INDEX IF NOT EXISTS ix_historico_paciente_prestador ON historico_paciente (prestador_id)",
            "CREATE INDEX IF NOT EXISTS ix_historico_paciente_data ON historico_paciente (clinica_id, paciente_id, data, id)",
        ):
            conn.execute(text(statement))


def downgrade() -> None:
    with engine.begin() as conn:
        conn.execute(text("DROP TABLE IF EXISTS historico_paciente"))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--downgrade", action="store_true")
    args = parser.parse_args()
    (downgrade if args.downgrade else upgrade)()


if __name__ == "__main__":
    main()
