import { useEffect, useMemo, useState } from 'react';
import { Button, Input, Modal, Select, Spin } from 'antd';
import { listarMenuPacientes, listarMenuPacientesOptions, menuPacientesDefaults, obterMenuPaciente } from '../api/menuPacientesApi.js';
import '../menuPacientes.css';

const LETTERS = ['*', ...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'];
const patientName = (p) => p?.nome_completo ?? p?.nomeCompleto ?? p?.nome_paciente ?? p?.name ?? p?.nome ?? p?.patientName ?? '';
const patientId = (p) => p?.id ?? p?.patientId ?? p?.nro_pac ?? '';
export function mapAgendaPatientToDraft(p) { return { patientId: String(patientId(p)), name: patientName(p), phones: [p.fone1 ?? p.telefone1 ?? '', p.fone2 ?? '', p.fone3 ?? ''], phoneTypes: [p.tip_fone1 ?? 'Residencial', p.tip_fone2 ?? 'Celular', p.tip_fone3 ?? 'Comercial'], tip_fone1: p.tip_fone1 ?? 'Residencial', fone1: p.fone1 ?? p.telefone1 ?? '', tip_fone2: p.tip_fone2 ?? 'Celular', fone2: p.fone2 ?? '', tip_fone3: p.tip_fone3 ?? 'Comercial', fone3: p.fone3 ?? '' }; }
const optionsFor = (data, key) => (Array.isArray(data?.[key]) ? data[key].map((item) => ({ value: Number(item.id), label: item.label })) : []);

export function MenuPacientesModal({ open, onCancel, onSelect, initialQuery = '' }) {
  const [options, setOptions] = useState({}); const [preferences, setPreferences] = useState(menuPacientesDefaults); const [query, setQuery] = useState('');
  const [result, setResult] = useState({ total: 0, items: [], coluna2_label: 'Número' }); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [selectedId, setSelectedId] = useState(null); const [selecting, setSelecting] = useState(false);
  useEffect(() => { if (!open) return undefined; setQuery(initialQuery); setSelectedId(null); const c = new AbortController(); listarMenuPacientesOptions({ signal: c.signal }).then(setOptions).catch((e) => { if (e.name !== 'AbortError') setError('Não foi possível carregar as opções.'); }); return () => c.abort(); }, [open, initialQuery]);
  useEffect(() => { if (!open) return undefined; const c = new AbortController(); setLoading(true); setError(''); listarMenuPacientes({ ...preferences, q: query, offset: 0, limit: 5000, signal: c.signal }).then((p) => setResult({ total: Number(p?.total || 0), items: Array.isArray(p?.items) ? p.items : [], coluna2_label: p?.coluna2_label || 'Número' })).catch((e) => { if (e.name !== 'AbortError') setError('Não foi possível carregar os pacientes.'); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [open, preferences, query]);
  const selected = useMemo(() => result.items.find((p) => String(patientId(p)) === String(selectedId)), [result.items, selectedId]);
  const selectPatient = async (p) => { setSelecting(true); try { onSelect?.({ ...p, ...(await obterMenuPaciente(patientId(p))) }); } catch { onSelect?.(p); } finally { setSelecting(false); } };
  const setPreference = (key) => (value) => setPreferences((current) => ({ ...current, [key]: Number(value) }));
  return <Modal open={open} title="Menu de pacientes" className="agenda-patient-search-modal" width={690} footer={null} destroyOnClose onCancel={onCancel}><div className="agenda-patient-search__grid"><div className="agenda-patient-search__filters"><label>Cirurgião:<Select aria-label="Cirurgião" value={preferences.cir_menu_pac} options={optionsFor(options, 'cirurgioes')} onChange={setPreference('cir_menu_pac')} /></label><label>Filtro:<Select aria-label="Filtro" value={preferences.status_menu_pac} options={optionsFor(options, 'filtro_status')} onChange={setPreference('status_menu_pac')} /></label><label>Visualização:<Select aria-label="Visualização" value={preferences.visualizacao_menu_pac} options={optionsFor(options, 'visualizacao')} onChange={setPreference('visualizacao_menu_pac')} /></label></div><label>Pesquisar nome do paciente:<Input aria-label="Pesquisar nome do paciente" value={query} onChange={(e) => setQuery(e.target.value)} /></label><div className="agenda-patient-search__letters" aria-label="Filtro alfabético">{LETTERS.map((item) => { const value = item === '*' ? 0 : item.charCodeAt(0) - 64; return <Button key={item} type={preferences.active_ord_menu_pac === value ? 'primary' : 'default'} onClick={() => setPreferences((current) => ({ ...current, active_ord_menu_pac: value }))}>{item}</Button>; })}</div><div className="agenda-patient-search__table-wrap">{loading ? <div className="agenda-patient-search__message"><Spin aria-label="Carregando pacientes" /></div> : error ? <div role="alert" className="agenda-patient-search__message">{error}</div> : result.items.length ? <table className="agenda-patient-search__table"><thead><tr><th>Nome</th><th>{result.coluna2_label}</th></tr></thead><tbody>{result.items.map((p) => { const id = patientId(p); return <tr key={String(id)} className={String(selectedId) === String(id) ? 'selected' : ''} onClick={() => setSelectedId(id)} onDoubleClick={() => selectPatient(p)}><td>{p.nome ?? patientName(p)}</td><td>{p.valor_coluna2 ?? ''}</td></tr>; })}</tbody></table> : <div className="agenda-patient-search__message">Nenhum paciente encontrado</div>}</div><div className="agenda-patient-search__footer"><span>{result.total} pacientes listados</span><div className="agenda-patient-search__actions"><Button disabled>Novo...</Button><Button disabled={!selected || selecting} onClick={() => selected && selectPatient(selected)}>Ok</Button><Button onClick={onCancel}>Cancela</Button></div></div></div></Modal>;
}
export { MenuPacientesModal as AgendaPatientSearchModal };
