from __future__ import annotations

from copy import deepcopy

PROCEDIMENTOS_BRANA_PADRAO = [
    {'codigo': 223, 'nome': 'Aparelho Autoligado (Arcada Inferior)'},
    {'codigo': 224, 'nome': 'Aparelho Autoligado (Arcada Superior)'},
    {'codigo': 225, 'nome': 'Aparelho de conten\x87Æo'},
    {'codigo': 226, 'nome': 'Aparelho em uma arcada conjugado c/ ap. auxiliar'},
    {'codigo': 227, 'nome': 'Aparelho extra bucal'},
    {'codigo': 228, 'nome': 'Aparelho Ortod\x93ntico Est\x82tico em Porcelana - (Arcada Inferior)'},
    {'codigo': 229, 'nome': 'Aparelho Ortod\x93ntico Est\x82tico em Porcelana - (Arcada Superior)'},
    {'codigo': 230, 'nome': 'Aparelho Ortod\x93ntico Est\x82tico em Zafira - (Arcada Inferior)'},
    {'codigo': 231, 'nome': 'Aparelho Ortod\x93ntico Est\x82tico em Zafira - (Arcada Superior)'},
    {'codigo': 232, 'nome': 'Aparelho Ortod\x93ntico Fixo - (Arcada Inferior)'},
    {'codigo': 233, 'nome': 'Aparelho Ortod\x93ntico Fixo - (Arcada Superior)'},
    {'codigo': 234, 'nome': 'Aparelho Ortopedico'},
    {'codigo': 235, 'nome': 'Aparelho removivel'},
    {'codigo': 236, 'nome': 'Aparelhos auxiliares (extra-oral, "Bumper", etc)'},
    {'codigo': 237, 'nome': 'Arco Palatino'},
    {'codigo': 238, 'nome': 'Ativador de Haulp'},
    {'codigo': 239, 'nome': 'Ativador de Rossi'},
    {'codigo': 240, 'nome': 'Ativador de Zurick - Su¡\x87a'},
    {'codigo': 241, 'nome': 'Bandagem (Tubo bracket)'},
    {'codigo': 242, 'nome': 'Bandagem (Tubo duplo)'},
    {'codigo': 243, 'nome': 'Bandagem (Tubo simples)'},
    {'codigo': 244, 'nome': 'Bandagem (Tubo triplo)'},
    {'codigo': 245, 'nome': 'Barra Transpalatina'},
    {'codigo': 246, 'nome': 'Bi-h\x82lice'},
    {'codigo': 247, 'nome': 'Bio-ajustador - Tecnica MD3'},
    {'codigo': 248, 'nome': 'Bionator - Super'},
    {'codigo': 249, 'nome': 'Bionator de Balters - Classe I'},
    {'codigo': 250, 'nome': 'Bionator de Balters - Classe II'},
    {'codigo': 251, 'nome': 'Bionator de Balters - Classe III'},
    {'codigo': 252, 'nome': 'Blinler - A'},
    {'codigo': 253, 'nome': 'Blinler - B'},
    {'codigo': 254, 'nome': 'Blinler - C'},
    {'codigo': 255, 'nome': 'BotÆo de Nance'},
    {'codigo': 256, 'nome': 'Bracket (Bracket 0,18" x 0,25")'},
    {'codigo': 257, 'nome': 'Bracket (Bracket 0,18" x 0,30")'},
    {'codigo': 258, 'nome': 'Bracket (Bracket 0,22" x 0,28")'},
    {'codigo': 259, 'nome': 'Bracket (Bracket Straight-Wire)'},
    {'codigo': 260, 'nome': 'Conten\x87Æo Fixa Lingual'},
    {'codigo': 261, 'nome': 'Conten\x87Æo m¢vel - (Placa de acet to)'},
    {'codigo': 262, 'nome': 'Disjuntor de Hass'},
    {'codigo': 263, 'nome': 'Disjuntor de Hirax'},
    {'codigo': 264, 'nome': 'Disjuntor Hirax RC'},
    {'codigo': 265, 'nome': 'Disjuntor MC Namara - Resina'},
    {'codigo': 266, 'nome': 'Disjuntor MC Namara com Hirax'},
    {'codigo': 267, 'nome': 'Disjuntor Omar Gabriel'},
    {'codigo': 268, 'nome': 'Distabilizador Pendex com P\x88ndulo'},
    {'codigo': 269, 'nome': 'Djuntor palatino'},
    {'codigo': 270, 'nome': 'Documenta\x87Æo ortod\x93ntica'},
    {'codigo': 271, 'nome': 'Frankel - Classe I'},
    {'codigo': 272, 'nome': 'Frankel - Classe II'},
    {'codigo': 273, 'nome': 'Frankel - Classe III'},
    {'codigo': 274, 'nome': 'Frankel - Mordida Aberta'},
    {'codigo': 275, 'nome': 'Grade palatina fixa'},
    {'codigo': 276, 'nome': 'Grade palatina m¢vel'},
    {'codigo': 277, 'nome': 'Klammt - Classe I'},
    {'codigo': 278, 'nome': 'Klammt - Classe II'},
    {'codigo': 279, 'nome': 'Klammt - Classe III'},
    {'codigo': 280, 'nome': 'Lip Bumper'},
    {'codigo': 281, 'nome': 'Mantenedor de espa\x87o'},
    {'codigo': 282, 'nome': 'Manuten\x87Æo ortod\x93ntico - (Mensal)'},
    {'codigo': 283, 'nome': 'Mentoneira'},
    {'codigo': 284, 'nome': 'Ortopedia funcional dos maxilares'},
    {'codigo': 285, 'nome': 'Palatina ou arco lingual'},
    {'codigo': 286, 'nome': 'Placa 7/7'},
    {'codigo': 287, 'nome': 'Placa acoplada ao uso de arco extra bucal'},
    {'codigo': 288, 'nome': 'Placa ativa com molas'},
    {'codigo': 289, 'nome': 'Placa com arco al\x87a dupla para expan\x87Æo Y'},
    {'codigo': 290, 'nome': 'Placa com arco de conten\x87Æo cont¡nua'},
    {'codigo': 291, 'nome': 'Placa com arco de conten\x87Æo de Baag'},
    {'codigo': 292, 'nome': 'Placa com arco de controle dos caninos'},
    {'codigo': 293, 'nome': 'Placa com arco seccionado para uso elasticos'},
    {'codigo': 294, 'nome': 'Placa com plano de mordida inclinado'},
    {'codigo': 295, 'nome': 'Placa com plano de mordida posterior'},
    {'codigo': 296, 'nome': 'Placa com plano reto anterior'},
    {'codigo': 297, 'nome': 'Placa de Apn\x82ia'},
    {'codigo': 298, 'nome': 'Placa de ativa\x87Æo mandibular'},
    {'codigo': 299, 'nome': 'Placa de Eschler'},
    {'codigo': 300, 'nome': 'Placa de expansÆo para mordida cruzada'},
    {'codigo': 301, 'nome': 'Placa de Hawley'},
    {'codigo': 302, 'nome': 'Placa de Hawley invertido'},
    {'codigo': 303, 'nome': 'Placa de Mills'},
    {'codigo': 304, 'nome': 'Placa de ocupa\x87Æo lingual'},
    {'codigo': 305, 'nome': 'Placa de Roberts'},
    {'codigo': 306, 'nome': 'Placa dupla de avan\x87o - Piamant'},
    {'codigo': 307, 'nome': 'Placa interceptora de h bito'},
    {'codigo': 308, 'nome': 'Placa labial ativa'},
    {'codigo': 309, 'nome': 'Placa mantenedora de espa\x87o.'},
    {'codigo': 310, 'nome': 'Placa recuperadora de espa\x87o'},
    {'codigo': 311, 'nome': 'Planas Compostas'},
    {'codigo': 312, 'nome': 'Planas Simples'},
    {'codigo': 313, 'nome': 'Quadri-h\x82lice'},
    {'codigo': 314, 'nome': 'Spling Retainer 3/3 4/4'},
    {'codigo': 315, 'nome': 'Twin Black'},
    {'codigo': 316, 'nome': 'Vilma Simäes - SN1, SN2, SN3, SN4, SN5'},
    {'codigo': 317, 'nome': 'Vilma Simäes - SN6, SN7'},
    {'codigo': 323, 'nome': 'Alinhadores Est\x82ticos'},
    {'codigo': 336, 'nome': 'Remo\x87Æo de aparelho ortodontico fixo.'},
    {'codigo': 1000, 'nome': 'Aplica\x87Æo de Cariost tico - (sessÆo)'},
    {'codigo': 1010, 'nome': 'Aplica\x87Æo de Fl£or Verniz - (por elemento)'},
    {'codigo': 1020, 'nome': 'Aplica\x87Æo de Selnate Oclusa Invasivo - (por elemento)'},
    {'codigo': 1030, 'nome': 'Aplica\x87Æo T¢pica de Fl£or'},
    {'codigo': 1040, 'nome': 'Controle da Placa Bacteriana - (por sessÆo)'},
    {'codigo': 1050, 'nome': 'Instru\x87Æo de Higiene Oral - (I.H.O.)'},
    {'codigo': 1060, 'nome': 'Profilaxia - (Polimento com ta\x87a de borracha)'},
    {'codigo': 1070, 'nome': 'Profilaxia - (Ultrason e Jato de Bicarbonato)'},
    {'codigo': 1080, 'nome': 'Teste de fluxo salivar'},
    {'codigo': 1090, 'nome': 'Teste de Risco de C rie'},
    {'codigo': 2000, 'nome': 'Cimenta\x87Æo de Coroa Total Definitiva'},
    {'codigo': 2010, 'nome': 'Cimenta\x87Æo de Coroa Total Provis¢ria'},
    {'codigo': 2011, 'nome': 'Cimenta\x87Æo adesiva'},
    {'codigo': 2020, 'nome': 'Cimenta\x87Æo de N£cleo Met lico Fundido'},
    {'codigo': 2030, 'nome': 'Cimenta\x87Æo de Pr¢tese Parcial Fixa'},
    {'codigo': 2040, 'nome': 'Consulta de adapta\x87Æo Psicol¢gica'},
    {'codigo': 2050, 'nome': 'Consulta de Emerg\x88ncia'},
    {'codigo': 2060, 'nome': 'Consulta de Emerg\x88ncia - (S bado, Domingo e Feriado)'},
    {'codigo': 2070, 'nome': 'Consulta de Emerg\x88ncia Noturna - (22:00 s 06:00 hs)'},
    {'codigo': 2080, 'nome': 'Consulta Inicial para Exame cl¡nico'},
    {'codigo': 2081, 'nome': 'Consulta de Reavalia\x87Æo Cl¡nica'},
    {'codigo': 2090, 'nome': 'Curativo'},
    {'codigo': 2100, 'nome': 'Exame para Per¡cia Inicial e Final'},
    {'codigo': 2110, 'nome': 'Modelo de Estudo - (Superior e Infeiror)'},
    {'codigo': 2111, 'nome': 'Foto extra-oral'},
    {'codigo': 2120, 'nome': 'Radiografia Bite-Wing - (inter-proximal)'},
    {'codigo': 2130, 'nome': 'Radiografia Oclusal'},
    {'codigo': 2140, 'nome': 'Radiografia Periapical'},
    {'codigo': 3000, 'nome': 'Abertura de implante - (Giro de retalho)'},
    {'codigo': 3010, 'nome': 'Abertura de implante - (Osteotomia)'},
    {'codigo': 3020, 'nome': 'Abertura de implante - (Plastia)'},
    {'codigo': 3030, 'nome': 'Abertura de implante mand. - (Enxerto Livre)'},
    {'codigo': 3040, 'nome': 'Abertura de implante mand. - (Osteotomia e Livre)'},
    {'codigo': 3050, 'nome': 'Aumento de Coroa Cl¡nica - (Osteotomia e deslize apical)'},
    {'codigo': 3060, 'nome': 'Aumento de Coroa Cl¡nica - (Osteotomia)'},
    {'codigo': 3070, 'nome': 'Aumento de Coroa Cl¡nica - (Plastia)'},
    {'codigo': 3080, 'nome': 'Bridectomia'},
    {'codigo': 3090, 'nome': 'Cirurgia para colagem de botÆo Ortod\x93ntico'},
    {'codigo': 3100, 'nome': 'Cirurgia para colagem de botÆo Ortod\x93ntico com osteotomia'},
    {'codigo': 3110, 'nome': 'Cirurgia para Odonto-sec\x87Æo - (por elemento)'},
    {'codigo': 3120, 'nome': 'Cirurgia para Rizectomia'},
    {'codigo': 3130, 'nome': 'Enxerto de conjuntivo / tuneliza\x87Æo'},
    {'codigo': 3140, 'nome': 'Cirurgia Periodontal a retalho - (1 elemento)'},
    {'codigo': 3150, 'nome': 'Cirurgia Periodontal a retalho - (por segmento)'},
    {'codigo': 3160, 'nome': 'Cunha Distal ou Proximal'},
    {'codigo': 3170, 'nome': 'Enxerto de Tecido Conjuntivo'},
    {'codigo': 3180, 'nome': 'Enxerto Gengival Livre'},
    {'codigo': 3190, 'nome': 'Enxerto Osseo RTG - (Regenera\x87Æo Tecidual Guiada)'},
    {'codigo': 3200, 'nome': 'Enxerto Pediculado - (por elemento)'},
    {'codigo': 3210, 'nome': 'Enxerto por Tracionamento de Vestibulo - (por elemento)'},
    {'codigo': 3220, 'nome': 'Enxerto por Tracionamento de Vestibulo - (por segmento)'},
    {'codigo': 3230, 'nome': 'Frenectomia labial inferior'},
    {'codigo': 3240, 'nome': 'Frenectomia labial superior'},
    {'codigo': 3250, 'nome': 'Frenotomia L bial Inferior'},
    {'codigo': 3260, 'nome': 'Frenotomia L bial Superior'},
    {'codigo': 3270, 'nome': 'Frenotomia Lingual'},
    {'codigo': 3280, 'nome': 'Gengivectomia ou Gengivoplastia - (por elemento)'},
    {'codigo': 3290, 'nome': 'Gengivectomia ou Gengivoplastia - (por segmento)'},
    {'codigo': 3300, 'nome': 'Gengivectomia palatina / lingual - (por elemento)'},
    {'codigo': 3310, 'nome': 'Gengivectomia palatina / lingual - (por segmento)'},
    {'codigo': 3320, 'nome': 'Manuten\x87Æo Periodontal - (por sessÆo)'},
    {'codigo': 3330, 'nome': 'Raspagem Sub-gengival e Curetagem de bolsa - (por segmento)'},
    {'codigo': 3340, 'nome': 'Raspagem Supra-gengival - (por segmento)'},
    {'codigo': 3350, 'nome': 'Remo\x87Æo de Fatores de Reten\x87Æo - (por segmento)'},
    {'codigo': 3360, 'nome': 'Sepultamento Radicular - (por raiz)'},
    {'codigo': 3370, 'nome': 'Ulectomia'},
    {'codigo': 4000, 'nome': 'Apicectomia em Incisivos com enxerto leofilizado'},
    {'codigo': 4010, 'nome': 'Apicectomia em Incisivos com obtura\x87Æo retr¢grada'},
    {'codigo': 4020, 'nome': 'Apicectomia em Incisivos curetagem apical'},
    {'codigo': 4030, 'nome': 'Apicectomia em Molares com enxerto leofilizado'},
    {'codigo': 4040, 'nome': 'Apicectomia em Molares com obtura\x87Æo retr¢grada'},
    {'codigo': 4050, 'nome': 'Apicectomia em Molares curetagem apical'},
    {'codigo': 4060, 'nome': 'Apicectomia em Pr\x82-molares com enxerto leofilizado'},
    {'codigo': 4070, 'nome': 'Apicectomia em Pr\x82-molares com obtura\x87Æo retr¢grada'},
    {'codigo': 4080, 'nome': 'Apicectomia em Pr\x82-molares curetagem apical'},
    {'codigo': 4090, 'nome': 'Clareamento Interno'},
    {'codigo': 4100, 'nome': 'Desobtura\x87Æo de canal'},
    {'codigo': 4110, 'nome': 'Preparo para N£cleo intra-radicular'},
    {'codigo': 4120, 'nome': 'Pulpotomia'},
    {'codigo': 4130, 'nome': 'Reimplante dentes avuls. trauma + ap. conten\x87Æo'},
    {'codigo': 4140, 'nome': 'Remo\x87Æo de Coroal Total'},
    {'codigo': 4150, 'nome': 'Remo\x87Æo de n£cleo intraradicular'},
    {'codigo': 4160, 'nome': 'Retratamento de Canal - (Incisivos)'},
    {'codigo': 4170, 'nome': 'Retratamento de Canal - (Molares com 4 ou mais condutos)'},
    {'codigo': 4180, 'nome': 'Retratamento de Canal - (Molares)'},
    {'codigo': 4190, 'nome': 'Retratamento de Canal - (Pr\x82-molares)'},
    {'codigo': 4200, 'nome': 'Tratamento cirurgico de lesÆo endo-perio - (Curetagem)'},
    {'codigo': 4210, 'nome': 'Tratamento cirurgico de lesÆo endo-perio com enxerto leofilizado'},
    {'codigo': 4220, 'nome': 'Tratamento de Canal - (Incisivos)'},
    {'codigo': 4230, 'nome': 'Tratamento de Canal - (Molares com mais de 3 condutos)'},
    {'codigo': 4240, 'nome': 'Tratamento de Canal - (Molares)'},
    {'codigo': 4250, 'nome': 'Tratamento de Canal - (Pr\x82-molares)'},
    {'codigo': 4260, 'nome': 'Tratamento de dentes c/ rizogenese incompleta - (Por sessÆo)'},
    {'codigo': 4270, 'nome': 'Tratamento de Trepana\x87äes / Perfura\x87äes'},
    {'codigo': 5000, 'nome': 'Adequao de meio bucal'},
    {'codigo': 5010, 'nome': 'Ajuste oclusal - (por sesso)'},
    {'codigo': 5020, 'nome': 'Capeamento pulpar'},
    {'codigo': 5030, 'nome': 'Clareamento - (Caseiro)'},
    {'codigo': 5040, 'nome': 'Clareamento - (Laser)'},
    {'codigo': 5050, 'nome': 'Clareamento interno - (dentes desvitalizados)'},
    {'codigo': 5060, 'nome': 'Dessensibiliza\x87Æo dent ria - (por elemento)'},
    {'codigo': 5070, 'nome': 'Faceta em resina direta - (Dentes anteriores)'},
    {'codigo': 5080, 'nome': 'Imobiliza\x87Æo dent ria com resina fotopolimeriz vel'},
    {'codigo': 5090, 'nome': 'Imobiliza\x87Æo dent ria (esplintagem)'},
    {'codigo': 5100, 'nome': 'N£cleo de preenchimento em ion\x93metro de vidro'},
    {'codigo': 5110, 'nome': 'N£cleo de preenchimento em resina'},
    {'codigo': 5120, 'nome': 'N£cleo fibra de vidro'},
    {'codigo': 5121, 'nome': 'N£cleo de preenchimento'},
    {'codigo': 5130, 'nome': 'N£cleo met lico pr\x82-fabricado'},
    {'codigo': 5140, 'nome': 'N£cleo rosqueavel - (Roach)'},
    {'codigo': 5150, 'nome': 'Polimento e Acabamento'},
    {'codigo': 5160, 'nome': 'Reconstru\x87Æo em Resina Direta - (+ de 3 Faces)'},
    {'codigo': 5170, 'nome': 'Restaura\x87Æo de Am lgama - 1 face'},
    {'codigo': 5180, 'nome': 'Restaura\x87Æo de Am lgama - 2 faces'},
    {'codigo': 5190, 'nome': 'Restaura\x87Æo de Am lgama - 3 faces'},
    {'codigo': 5200, 'nome': 'Procedimento 5200'},
    {'codigo': 5210, 'nome': 'Restaura\x87Æo em Resina Direta - (1 Face)'},
    {'codigo': 5220, 'nome': 'Restaura\x87Æo em Resina Direta - (2 Faces)'},
    {'codigo': 5230, 'nome': 'Restaura\x87Æo em Resina Direta - (3 Faces)'},
    {'codigo': 5240, 'nome': 'Restaura\x87Æo em Resina Direta - (Classe IV)'},
    {'codigo': 5250, 'nome': 'Restaura\x87Æo em Resina Direta - (Classe V)'},
    {'codigo': 5260, 'nome': 'Restaura\x87Æo tempor ria (IRM ou similar)'},
    {'codigo': 5270, 'nome': 'Tratamento Expectante com H. C lcio'},
    {'codigo': 6000, 'nome': 'Alveoloplastia ou alveolotomia - (at\x82 3 elementos)'},
    {'codigo': 6010, 'nome': 'Alveoloplastica ou alveolotomia - (por sextante)'},
    {'codigo': 6020, 'nome': 'Bi¢psia'},
    {'codigo': 6030, 'nome': 'Cirurgia de Hipertrofia de L bio'},
    {'codigo': 6040, 'nome': 'Cirurgia para Cisto de Desenvolvimento'},
    {'codigo': 6050, 'nome': 'Cirurgia para Microstomia'},
    {'codigo': 6060, 'nome': 'Cirurgia para Osteoma e Odontoma'},
    {'codigo': 6070, 'nome': 'Cirurgia para torus palatino unilateral'},
    {'codigo': 6080, 'nome': 'Ciurgia para torus mandibular bilateral'},
    {'codigo': 6090, 'nome': 'Ciurgia para t¢rus mandibular unilateral'},
    {'codigo': 6100, 'nome': 'Cirurgia para torus palatino bilateral'},
    {'codigo': 6110, 'nome': 'Corre\x87Æo de bridas musculares'},
    {'codigo': 6120, 'nome': 'Drenagem de abcesso por via intra ou extra-oral'},
    {'codigo': 6130, 'nome': 'Cirurgia explorat¢ria'},
    {'codigo': 6140, 'nome': 'ExcisÆo de gl\x83ndula par¢tida'},
    {'codigo': 6150, 'nome': 'ExcisÆo de gl\x83ndula sublingual'},
    {'codigo': 6160, 'nome': 'ExcisÆo de gl\x83ndula submandibular'},
    {'codigo': 6170, 'nome': 'ExcisÆo de Mucocele'},
    {'codigo': 6180, 'nome': 'ExcisÆo de r\x83nula'},
    {'codigo': 6190, 'nome': 'ExcisÆo de tumores odontog\x88nicos at\x82 3 cm'},
    {'codigo': 6200, 'nome': 'Exodontia de dec¡duos'},
    {'codigo': 6210, 'nome': 'Exodontia de incluso'},
    {'codigo': 6220, 'nome': 'Exodontia de incluso impactado'},
    {'codigo': 6230, 'nome': 'Exodontia de raiz residual'},
    {'codigo': 6240, 'nome': 'Exodontia de raiz residual com retalho'},
    {'codigo': 6250, 'nome': 'Exodontia de semi-incluso'},
    {'codigo': 6260, 'nome': 'Exodontia + Enxerto + membrana'},
    {'codigo': 6270, 'nome': 'Exodontia simples - (Anteriores)'},
    {'codigo': 6280, 'nome': 'Exodontia simples - (Posteriores)'},
    {'codigo': 6290, 'nome': 'Fraturas alv\x82dio-dent rias - redu\x87Æo cruenta'},
    {'codigo': 6300, 'nome': 'Marzupializa\x87Æo de cisto'},
    {'codigo': 6310, 'nome': 'Reconstru\x87Æo parcial do l bio traumatizado'},
    {'codigo': 6320, 'nome': 'Reconstru\x87Æo total do l bio traumatizado'},
    {'codigo': 6330, 'nome': 'Suturas m£ltiplas da face ou l bio'},
    {'codigo': 6340, 'nome': 'Suturas simples da face ou l bio'},
    {'codigo': 6350, 'nome': 'Tratamento de alveolite'},
    {'codigo': 6360, 'nome': 'Tratamento de hemorragia'},
    {'codigo': 6370, 'nome': 'Tratamento cir£rgico do l bio leporino'},
    {'codigo': 7000, 'nome': 'Implante - (t\x82cnica de Sammers)'},
    {'codigo': 7010, 'nome': 'Implante (RTG)'},
    {'codigo': 7020, 'nome': 'Implante ¢sseo integr vel - Standard'},
    {'codigo': 7021, 'nome': 'Implante ¢sseo integr vel - H. Interno'},
    {'codigo': 7022, 'nome': 'Implante ¢sseo integr vel - Cone Morse'},
    {'codigo': 7023, 'nome': 'Implante Cone Morse + Enxerto'},
    {'codigo': 7030, 'nome': 'Remo\x87Æo de implante'},
    {'codigo': 7040, 'nome': 'Enxerto Osseo Particulado + Membrana colageno.'},
    {'codigo': 7050, 'nome': 'Levanto de seio maxilar'},
    {'codigo': 7060, 'nome': 'Implante Zigom tico'},
    {'codigo': 7070, 'nome': 'Regenera\x87Æo ¢ssea guiada - ROG'},
    {'codigo': 8000, 'nome': 'Attachment'},
    {'codigo': 8010, 'nome': 'Casquete de moldagem'},
    {'codigo': 8020, 'nome': 'Conserto de Pr¢tese Total e Parcial'},
    {'codigo': 8030, 'nome': 'Coroa em Resina Prensada'},
    {'codigo': 8040, 'nome': 'Coroa em Resina Sinfony'},
    {'codigo': 8050, 'nome': 'Coroa em Resina sob implante'},
    {'codigo': 8060, 'nome': 'Coroa Metal-free - (Cerampress)'},
    {'codigo': 8070, 'nome': 'Coroa Metal-free - (Inceram)'},
    {'codigo': 8080, 'nome': 'Coroa Metal-free - (Procera)'},
    {'codigo': 8090, 'nome': 'Coroa Metal-free - (Zirconia; Sistema CAD/CAM)'},
    {'codigo': 8100, 'nome': 'Coroa Metal-free sob implante - (Cerampress)'},
    {'codigo': 8110, 'nome': 'Coroa Metal-free sob implante - (Inceram)'},
    {'codigo': 8120, 'nome': 'Coroa Metal-free sob implante - (Procera)'},
    {'codigo': 8130, 'nome': 'Coroa Metal-free sob implante - (Zirconia; Sistema CAD/CAM)'},
    {'codigo': 8140, 'nome': 'Coroa metalo-cer\x83mica'},
    {'codigo': 8150, 'nome': 'Coroa Metalo-cer\x83mica sob implante'},
    {'codigo': 8151, 'nome': 'MunhÆo Universal - CM'},
    {'codigo': 8160, 'nome': 'Coroa Provis¢ria Imediata'},
    {'codigo': 8161, 'nome': 'Coroa Provis¢ria de Onlay / Inlay'},
    {'codigo': 8170, 'nome': 'Coroa Provis¢ria de Laborat¢rio sob implante'},
    {'codigo': 8171, 'nome': 'Coroa Provis¢ria Imediata sob implante'},
    {'codigo': 8180, 'nome': 'Coroa met lica total'},
    {'codigo': 8190, 'nome': 'Coroa Provis¢ria de Laborat¢rio'},
    {'codigo': 8200, 'nome': 'Enceramento de diagn¢stico - (por elemento)'},
    {'codigo': 8210, 'nome': 'Enceramento de diagn¢stico por elemento sob implante'},
    {'codigo': 8220, 'nome': 'Faceta em Porcelana'},
    {'codigo': 8230, 'nome': 'Faceta em Resina Acrilica'},
    {'codigo': 8240, 'nome': 'Guia Cirurgico'},
    {'codigo': 8250, 'nome': 'Jig ou Front-Plat\x93'},
    {'codigo': 8260, 'nome': 'N£cleo Met lico-fundido'},
    {'codigo': 8261, 'nome': 'N£cleo Met lico fundido bi-partido'},
    {'codigo': 8270, 'nome': 'N£cleo Metal-free est\x82tico'},
    {'codigo': 8290, 'nome': 'Placa de mordida miorrelaxante'},
    {'codigo': 8291, 'nome': 'Protetor bucal Playsafe'},
    {'codigo': 8292, 'nome': 'Protetor bucal Playsafe Personalizado'},
    {'codigo': 8300, 'nome': 'Placa para Bruxismo Acr¡lica'},
    {'codigo': 8305, 'nome': 'Placa para Bruxismo Mista - (Erkoflex)'},
    {'codigo': 8310, 'nome': 'Placa para Clareamento'},
    {'codigo': 8315, 'nome': 'Placa para Ortose'},
    {'codigo': 8320, 'nome': 'Pr¢tese Parcial Fixa Adesiva Metal-free'},
    {'codigo': 8330, 'nome': 'Pr¢tese Parcial Fixa Acrilica sob Implante'},
    {'codigo': 8340, 'nome': 'Pr¢tese Parcial Fixa Metalo-cer\x83mica - (1 P\x93ntico)'},
    {'codigo': 8350, 'nome': 'Pr¢tese Parcial Fixa Metalo-cer\x83mica - (2 P\x93nticos)'},
    {'codigo': 8360, 'nome': 'Pr¢tese Parcial Fixa Metalo-plastica - (1 P\x93ntico)'},
    {'codigo': 8361, 'nome': 'Pr¢tese Parcial Fixa Metalo-plastica - (2 P\x93nticos)'},
    {'codigo': 8370, 'nome': 'Pr¢tese Parcial Fixa Provis¢ria - (1 P\x93ntico)'},
    {'codigo': 8380, 'nome': 'Pr¢tese Parcial Remov¡vel - (Importada) / (por arcada)'},
    {'codigo': 8390, 'nome': 'Pr¢tese Parcial Remov¡vel - (por arcada)'},
    {'codigo': 8400, 'nome': 'Pr¢tese Parcial Remov¡vel Provis¢ria - (por arcada)'},
    {'codigo': 8410, 'nome': 'Pr¢tese Total - (Importada) / (por arcada)'},
    {'codigo': 8420, 'nome': 'Pr¢tese Total - (por arcada)'},
    {'codigo': 8430, 'nome': 'Pr¢tese Total Imediada - (por arcada)'},
    {'codigo': 8440, 'nome': 'Pr¢tese Protocolo'},
    {'codigo': 8450, 'nome': 'Reembasamento de Coroa Provis¢ria'},
    {'codigo': 8460, 'nome': 'Reembasamento Pr¢tese Total ou Parcial'},
    {'codigo': 8470, 'nome': 'Restaura\x87Æo Met lica Fundida - RMF'},
    {'codigo': 8480, 'nome': 'Restaura\x87Æo Onlay / Inlay em Porcelana'},
    {'codigo': 8481, 'nome': 'E-MAX - Restaura\x87Æo Onlay / Inlay em Dissilicato de l¡tio'},
    {'codigo': 8482, 'nome': 'E-MAX - Jaqueta pura em dissilicato'},
    {'codigo': 8490, 'nome': 'Restaura\x87Æo Onlay / Inlay em Ceromero'},
    {'codigo': 8500, 'nome': 'E-MAX - Lente de contato'},
    {'codigo': 9000, 'nome': 'Micro-agulhamento (Derma Roller)'},
    {'codigo': 9010, 'nome': 'Botox'},
    {'codigo': 9020, 'nome': 'Preenchimento'},
    {'codigo': 9030, 'nome': 'Lipo de papada'},
    {'codigo': 9040, 'nome': 'Fios de sustenta\x87Æo'},
    {'codigo': 9050, 'nome': 'Bichectomia'},
]

def get_procedimentos_brana_padrao():
    return deepcopy(PROCEDIMENTOS_BRANA_PADRAO)

__all__ = ['PROCEDIMENTOS_BRANA_PADRAO', 'get_procedimentos_brana_padrao']
