import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const projectRoot = process.cwd().endsWith(`${path.sep}frontend-react`)
  ? process.cwd()
  : path.resolve('frontend-react');

const read = (...segments) => fs.readFileSync(path.resolve(projectRoot, ...segments), 'utf8');

const appSource = read('src/app/App.jsx');
const toolbarSource = read('src/features/prestadores/PrestadoresToolbar.jsx');
const modalSource = read('src/features/agendaConfiguracao/AgendaConfiguracaoModal.jsx');
const constantsSource = read('src/features/agendaConfiguracao/agendaConfiguracaoConstants.js');
const bloqueiosContractsSource = read('src/features/agendaConfiguracao/agendaConfiguracaoBloqueios.js');
const cssSource = read('src/features/agendaConfiguracao/agendaConfiguracao.css');
const escalaSource = read('src/features/agendaConfiguracao/components/tabs/AgendaEscalaTab.jsx');
const bloqueiosTabSource = read('src/features/agendaConfiguracao/components/tabs/AgendaBloqueiosTab.jsx');
const bloqueioModalSource = read('src/features/agendaConfiguracao/components/bloqueios/AgendaBloqueioModal.jsx');
const apresentacaoSource = read('src/features/agendaConfiguracao/components/tabs/AgendaApresentacaoTab.jsx');
const colorDropdownSource = read('src/features/agendaConfiguracao/components/AgendaColorDropdown.jsx');
const colorsSource = read('src/features/agendaConfiguracao/agendaConfiguracaoColors.js');
const fonteContractsSource = read('src/features/agendaConfiguracao/agendaConfiguracaoFonte.js');
const fonteModalSource = read('src/features/agendaConfiguracao/components/fonte/AgendaFonteModal.jsx');
const visualizacaoSource = read('src/features/agendaConfiguracao/components/tabs/AgendaVisualizacaoTab.jsx');
const stateSource = read('src/features/agendaConfiguracao/agendaConfiguracaoState.js');

test('feature agenda configuracao nasce fora de Prestadores e com contrato compartilhado', () => {
  assert.match(constantsSource, /AGENDA_CONFIGURACAO_TITLE = 'Configura horários de agendamento'/);
  assert.match(constantsSource, /source = 'prestadores'/);
  assert.match(constantsSource, /allowPrestadorChange = false/);
  assert.match(constantsSource, /selectedPrestadorSnapshot = null/);
  assert.match(constantsSource, /AGENDA_CONFIGURACAO_TABS/);
  assert.match(bloqueiosContractsSource, /AGENDA_BLOQUEIO_DIA_OPTIONS/);
  assert.match(bloqueiosContractsSource, /buildAgendaBloqueioDraft/);
  assert.match(bloqueiosContractsSource, /buildAgendaBloqueioPayload/);
  assert.match(modalSource, /BranaModal/);
  assert.match(modalSource, /AgendaConfiguracaoModal/);
  assert.match(constantsSource, /Configura horários de agendamento/);
  assert.match(modalSource, /Escala/);
  assert.match(modalSource, /Bloqueios/);
  assert.doesNotMatch(modalSource, /Contexto:/);
  assert.match(bloqueiosTabSource, /AgendaBloqueiosTab/);
  assert.match(bloqueioModalSource, /AgendaBloqueioModal/);
  assert.match(bloqueiosTabSource, /const bloqueiosItens = Array\.isArray\(bloqueios\)/);
  assert.match(bloqueiosTabSource, /bloqueiosLoading/);
  assert.match(bloqueiosTabSource, /bloqueiosError/);
  assert.match(bloqueiosTabSource, /createAgendaBloqueio/);
  assert.match(bloqueiosTabSource, /updateAgendaBloqueio/);
  assert.match(bloqueiosTabSource, /reloadBloqueios/);
  assert.match(bloqueiosTabSource, /Novo bloqueio/);
  assert.match(bloqueiosTabSource, /Altera/);
  assert.match(bloqueiosTabSource, /Elimina/);
  assert.match(bloqueiosTabSource, /bloqueiosItens/);
  assert.match(bloqueiosTabSource, /AgendaBloqueioModal/);
  assert.match(bloqueiosTabSource, /listarUnidadesAtendimentoCombos/);
  assert.match(bloqueiosTabSource, /agendaBloqueioDiaLabel/);
  assert.match(bloqueiosTabSource, /onDoubleClick/);
  assert.doesNotMatch(bloqueiosTabSource, /updateDraft\(\{\s*bloqueiosItens:/);
  assert.doesNotMatch(bloqueiosTabSource, /updateDraft\(\{\s*bloqueiosItens:\s*nextList/);
  assert.match(bloqueioModalSource, /Período de vigência/);
  assert.match(bloqueioModalSource, /Intervalo de horários/);
  assert.match(bloqueioModalSource, /Mensagem de alerta/);
  assert.match(bloqueioModalSource, /Dia da semana/);
  assert.match(bloqueioModalSource, /Unidade de atendimento/);
  assert.match(modalSource, /AgendaApresentacaoTab/);
  assert.match(modalSource, /AgendaVisualizacaoTab/);
  assert.match(modalSource, /visualizacao/);
  assert.match(apresentacaoSource, /Cor de fundo/);
  assert.match(apresentacaoSource, /Pacientes particulares/);
  assert.match(apresentacaoSource, /Pacientes de convênio/);
  assert.match(apresentacaoSource, /Compromissos/);
  assert.match(apresentacaoSource, /Altera letra\.\.\./);
  assert.match(apresentacaoSource, /AgendaFonteModal/);
  assert.match(apresentacaoSource, /Particular/);
  assert.match(apresentacaoSource, /Convênio/);
  assert.match(apresentacaoSource, /Compromisso/);
  assert.match(colorDropdownSource, /AgendaColorDropdown/);
  assert.match(colorDropdownSource, /onChange/);
  assert.match(colorDropdownSource, /role="listbox"/);
  assert.match(colorsSource, /AGENDA_APRESENTACAO_COLORS/);
  assert.match(colorsSource, /Amarelo/);
  assert.match(colorsSource, /Azul água/);
  assert.match(colorsSource, /Vermelho/);
  assert.match(cssSource, /agenda-color-dropdown__list/);
  assert.match(cssSource, /\.agenda-color-dropdown__list \{[\s\S]*position: absolute;[\s\S]*left: 0;[\s\S]*top: calc\(100% \+ 2px\);[\s\S]*width: 170px;/);
  assert.match(fonteModalSource, /Fonte/);
  assert.match(fonteModalSource, /Cancela/);
  assert.match(fonteModalSource, /Ok/);
  assert.match(fonteModalSource, /Estilo da fonte/);
  assert.match(fonteModalSource, /Tamanho/);
  assert.match(fonteModalSource, /Riscado/);
  assert.match(fonteModalSource, /Sublinhado/);
  assert.match(fonteModalSource, /Script/);
  assert.match(fonteModalSource, /AaBbYyZz/);
  assert.match(fonteContractsSource, /AGENDA_FONTE_DEFAULTS/);
  assert.match(fonteContractsSource, /MS Sans Serif/);
  assert.match(fonteContractsSource, /Oblíquo e negrito/);
  assert.match(stateSource, /AGENDA_VISUALIZACAO_FIELDS/);
  assert.match(stateSource, /AGENDA_VISUALIZACAO_DEFAULTS/);
  assert.match(stateSource, /Número do paciente/);
  assert.match(stateSource, /Número do prontuário/);
  assert.match(stateSource, /Nome do paciente/);
  assert.match(stateSource, /Matrícula/);
  assert.match(stateSource, /Convênio/);
  assert.match(stateSource, /Tabela/);
  assert.match(stateSource, /Fone 1/);
  assert.match(stateSource, /Fone 2/);
  assert.match(stateSource, /Fone 3/);
  assert.match(stateSource, /Sala/);
  assert.match(stateSource, /visualizacaoCampos/);
  assert.match(modalSource, /Cancela/);
  assert.match(modalSource, /Ok/);
  assert.match(modalSource, /const handleSave = async \(\) => \{[\s\S]*await save\(\);[\s\S]*\}/);
  assert.doesNotMatch(modalSource, /handleSave = async \(\) => \{[\s\S]*onCancel\?\.\(\);[\s\S]*\}/);
  assert.match(modalSource, /const handleCancel = \(\) => \{[\s\S]*resetFromBase\(\);[\s\S]*onCancel\?\.\(\);[\s\S]*\}/);
  assert.match(modalSource, /const handleFooterCancel = \(\) => \{[\s\S]*resetFromBase\(\);[\s\S]*\}/);
  assert.match(modalSource, /<Button onClick=\{handleFooterCancel\}>Cancela<\/Button>/);
  assert.match(modalSource, /disabled/);
  assert.match(modalSource, /activeTab/);
  assert.match(modalSource, /selectedPrestadorSnapshot/);
  assert.match(toolbarSource, /Agenda/);
  assert.match(escalaSource, /AgendaEscalaTab/);
  assert.match(bloqueiosTabSource, /AgendaBloqueiosTab/);
  assert.match(apresentacaoSource, /AgendaApresentacaoTab/);
  assert.match(visualizacaoSource, /AgendaVisualizacaoTab/);
  assert.doesNotMatch(modalSource, /requestJson\(/);
  assert.doesNotMatch(modalSource, /saveAgendaConfig|agendaConfiguracaoApi|POST/);
});

test('Agenda presentation colors use the full legacy palette with hex values', () => {
  assert.match(colorsSource, /#ffff00/);
  assert.match(colorsSource, /#0000ff/);
  assert.match(colorsSource, /#00e5ef/);
  assert.match(colorsSource, /#000080/);
  assert.match(colorsSource, /#ffffff/);
  assert.match(colorsSource, /#808080/);
  assert.match(colorsSource, /#d9d9d9/);
  assert.match(colorsSource, /#666666/);
  assert.match(colorsSource, /#c61ad9/);
  assert.match(colorsSource, /#8b4513/);
  assert.match(colorsSource, /#c0c0c0/);
  assert.match(colorsSource, /#000000/);
  assert.match(colorsSource, /#800080/);
  assert.match(colorsSource, /#008000/);
  assert.match(colorsSource, /#006400/);
  assert.match(colorsSource, /#00ff00/);
  assert.match(colorsSource, /#808000/);
  assert.match(colorsSource, /#ff0000/);
  assert.match(colorsSource, /AGENDA_APRESENTACAO_COLORS/);
  assert.match(colorDropdownSource, /selected\.value/);
  assert.match(colorDropdownSource, /aria-expanded/);
  assert.match(colorDropdownSource, /aria-selected/);
  assert.match(colorDropdownSource, /▼/);
});

test('Prestadores Toolbar liga Agenda ao handler externo e bloqueia sem selecao', () => {
  assert.match(toolbarSource, /onAgenda/);
  assert.doesNotMatch(toolbarSource, /agendaDisabled/);
  assert.match(toolbarSource, /disabled=\{!canRunSelectionActions \|\| !onAgenda\}/);
  assert.match(toolbarSource, /onClick=\{onAgenda\}/);
});

test('App cria contexto de agenda a partir do prestador selecionado sem abrir segundo modal', () => {
  assert.match(appSource, /AgendaConfiguracaoModal/);
  assert.match(appSource, /buildAgendaConfiguracaoContext/);
  assert.match(appSource, /const \[agendaConfiguracaoState, setAgendaConfiguracaoState\]/);
  assert.match(appSource, /openAgendaConfiguracao/);
  assert.match(appSource, /source:\s*'prestadores'/);
  assert.match(appSource, /source:\s*'configuracoes'/);
  assert.match(appSource, /allowPrestadorChange:\s*false/);
  assert.match(appSource, /selectedPrestadorSnapshot:\s*selected/);
  assert.match(appSource, /open=\{agendaConfiguracaoState\.open \|\| screen === 'agenda-configuracao'\}/);
  assert.match(appSource, /configuracao:\s*\[\s*\{ key: 'agendas', label: 'Agenda' \}/s);
  assert.match(appSource, /path === `\$\{base\}\/configuracoes\/agendas`/);
  assert.match(appSource, /screen === 'agenda-configuracao'/);
  assert.doesNotMatch(appSource, /second.*agenda|AgendaConfiguracaoModal.*App.*create.*two/i);
});

test('CSS base da agenda configuracao define tabs e footer sem inventar backend', () => {
  assert.match(cssSource, /agenda-configuracao-modal/);
  assert.match(cssSource, /agenda-configuracao-tabs/);
  assert.match(cssSource, /agenda-configuracao-footer/);
  assert.match(cssSource, /agenda-configuracao-context/);
  assert.match(cssSource, /agenda-bloqueios-toolbar/);
  assert.match(cssSource, /agenda-bloqueio-modal/);
  assert.match(cssSource, /:root\[data-brana-theme='dark'\]/);
  assert.doesNotMatch(cssSource, /requestJson|POST|PUT|DELETE/);
});
