import { Button, Checkbox, Modal } from 'antd';
import { useEffect, useState } from 'react';
import { detectCandidateFontFamilies, LEGACY_FONT_FAMILIES, normalizeLocalFontFamilies } from '../constants/localFontCandidates';

const FONTS = LEGACY_FONT_FAMILIES;
const STYLES = [{ value: 'normal', label: 'Regular', bold: false, italic: false }, { value: 'italic', label: 'Oblíquo', bold: false, italic: true }, { value: 'bold', label: 'Negrito', bold: true, italic: false }, { value: 'bold-italic', label: 'Oblíquo e negrito', bold: true, italic: true }];
const SIZES = [8, 9, 10, 11, 12, ...Array.from({ length: 30 }, (_, index) => 14 + index * 2)];
const COLORS = [{ value: '#000000', label: 'Preto' }, { value: '#800000', label: 'Bordô' }, { value: '#008000', label: 'Verde' }, { value: '#808000', label: 'Verde-oliva' }, { value: '#000080', label: 'Azul-marinho' }, { value: '#800080', label: 'Roxo' }, { value: '#008080', label: 'Azul-petróleo' }, { value: '#808080', label: 'Cinza' }, { value: '#c0c0c0', label: 'Prateado' }, { value: '#ff0000', label: 'Vermelho' }, { value: '#00ff00', label: 'Verde-limão' }, { value: '#ffff00', label: 'Amarelo' }, { value: '#0000ff', label: 'Azul' }, { value: '#ff00ff', label: 'Fúcsia' }, { value: '#00ffff', label: 'Azul-piscina' }, { value: '#ffffff', label: 'Branco' }];

function localFontFamilies(fonts) { return [...new Set(fonts.map((font) => font.family).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'pt-BR')); }

function OpenList({ label, value, options, onChange, className = '' }) { return <label className={`font-open-list ${className}`}>{label}:<select size={options.length > 10 ? 8 : options.length} value={value} onChange={(event) => onChange(event.target.value)} aria-label={label}>{options.map((item) => <option key={item.value ?? item} value={item.value ?? item}>{item.label ?? item}</option>)}</select></label>; }
function ColorList({ value, onChange }) { const [open, setOpen] = useState(false); const current = COLORS.find((item) => item.value === value) || COLORS[0]; return <div className="font-color-control"><span>Cor:</span><button type="button" className="font-color-trigger" onClick={() => setOpen((old) => !old)} aria-expanded={open}><i style={{ backgroundColor: current.value }} />{current.label}<span aria-hidden="true">▾</span></button>{open && <div className="font-color-options" role="listbox" aria-label="Cores">{COLORS.map((item) => <button type="button" role="option" aria-selected={item.value === value} key={item.value} onClick={() => { onChange(item.value); setOpen(false); }}><i style={{ backgroundColor: item.value }} />{item.label}</button>)}</div>}</div>; }

export function FontSettingsModal({ open, value, onCancel, onConfirm }) {
  const [v, setV] = useState(value || {}); const [fonts, setFonts] = useState(FONTS); const [localFontStatus, setLocalFontStatus] = useState(''); useEffect(() => { if (open) { setV(value || {}); setFonts((old) => old.includes(value?.fontFamily) ? old : value?.fontFamily ? [value.fontFamily, ...old] : old); setLocalFontStatus(''); } }, [open, value]); const set = (part) => setV((old) => ({ ...old, ...part }));
  const loadLocalFonts = async () => { if (typeof window !== 'undefined' && typeof window.queryLocalFonts === 'function') { try { const families = normalizeLocalFontFamilies(await window.queryLocalFonts()); if (families.length) { setFonts((old) => normalizeLocalFontFamilies([...families, v.fontFamily])); setLocalFontStatus(`${families.length} famílias locais carregadas.`); return; } setLocalFontStatus('Nenhuma fonte local retornada; catálogo compatível ativo.'); } catch (error) { if (error?.name === 'NotAllowedError') setLocalFontStatus('Permissão para fontes locais não concedida.'); else if (error?.name === 'SecurityError') setLocalFontStatus('Acesso local indisponível neste contexto seguro.'); else setLocalFontStatus('Acesso às fontes locais falhou; catálogo compatível ativo.'); } } const detected = detectCandidateFontFamilies(); if (detected?.length) { setFonts((old) => normalizeLocalFontFamilies([...detected, v.fontFamily])); setLocalFontStatus(`${detected.length} famílias candidatas detectadas.`); return; } setFonts((old) => normalizeLocalFontFamilies([...(old.length ? old : FONTS), v.fontFamily])); if (!localFontStatus) setLocalFontStatus('Catálogo compatível ativo.'); };
  const styleValue = v.bold && v.italic ? 'bold-italic' : v.bold ? 'bold' : v.italic ? 'italic' : 'normal';
  const previewStyle = { fontFamily: v.fontFamily, fontSize: v.fontSize, fontWeight: v.bold ? 700 : 400, fontStyle: v.italic ? 'italic' : 'normal', color: v.color, textDecoration: `${v.underline ? 'underline ' : ''}${v.strike ? 'line-through' : ''}`.trim() || 'none' };
  const effectStyle = { display: 'flex', alignItems: 'center', gap: 5, lineHeight: '20px', margin: 0 };
  return <Modal open={open} title="Fonte" onCancel={onCancel} width={580} className="font-settings-modal" footer={null}><div className="font-settings-open-grid"><div className="font-family-column"><OpenList label="Fonte" value={v.fontFamily || fonts[0]} options={fonts} onChange={(fontFamily) => set({ fontFamily })} className="font-family-list" /><Button size="small" onClick={loadLocalFonts}>Carregar fontes instaladas</Button><small className="local-font-status">{localFontStatus}</small></div><OpenList label="Estilo da fonte" value={styleValue} options={STYLES} onChange={(next) => { const selected = STYLES.find((item) => item.value === next) || STYLES[0]; set({ bold: selected.bold, italic: selected.italic }); }} className="font-style-list" /><OpenList label="Tamanho" value={String(v.fontSize || 16)} options={SIZES.map(String)} onChange={(fontSize) => set({ fontSize: Number(fontSize) })} className="font-size-list" /><div className="font-settings-actions"><Button type="primary" onClick={() => onConfirm(v)}>OK</Button><Button onClick={onCancel}>Cancelar</Button></div></div><div className="font-settings-lower-grid"><fieldset><legend>Efeitos</legend><Checkbox style={effectStyle} checked={!!v.strike} onChange={(event) => set({ strike: event.target.checked })}>Riscado</Checkbox><Checkbox style={effectStyle} checked={!!v.underline} onChange={(event) => set({ underline: event.target.checked })}>Sublinhado</Checkbox><ColorList value={v.color || '#000000'} onChange={(color) => set({ color })} /></fieldset><fieldset><legend>Exemplo</legend><div className="font-settings-preview" style={previewStyle}>AaBbYyZz</div><label className="font-script-field">Script:<select value={v.script || 'Ocidental'} onChange={(event) => set({ script: event.target.value })}><option value="Ocidental">Ocidental</option></select></label></fieldset></div><div className="font-settings-footer"><Button onClick={onCancel}>Cancelar</Button><Button type="primary" onClick={() => onConfirm(v)}>Ok</Button></div></Modal>;
}
