const SIMBOLO_GRAFICO_EDITOR_BASE_LIBRARY = [
  'sim_30.bmp',
  'sim_ajuste.bmp',
  'sim_attach.bmp',
  'sim_bra.bmp',
  'sim_bra_40.bmp',
  'sim_byte.bmp',
  'sim_default.bmp',
  'sim_down.bmp',
  'sim_face.bmp',
  'sim_face_40.bmp',
  'sim_modelo.bmp',
  'sim_outras.bmp',
  'sim_poli.bmp',
  'sim_prov.bmp',
  'sim_raiox.bmp',
  'sim_rx.bmp',
  'sim_sel.bmp',
  'sim_simb1.bmp',
  'sim_simb10.bmp',
  'sim_simb11.bmp',
  'sim_simb12.bmp',
  'sim_simb13.bmp',
  'sim_simb14.bmp',
  'sim_simb15.bmp',
  'sim_simb16.bmp',
  'sim_simb17.bmp',
  'sim_simb18.bmp',
  'sim_simb19.bmp',
  'sim_simb2.bmp',
  'sim_simb20.bmp',
  'sim_simb21.bmp',
  'sim_simb22.bmp',
  'sim_simb23.bmp',
  'sim_simb24.bmp',
  'sim_simb25.bmp',
  'sim_simb26.bmp',
  'sim_simb27.bmp',
  'sim_simb28.bmp',
  'sim_simb28_40.bmp',
  'sim_simb29.bmp',
  'sim_simb3.bmp',
  'sim_simb30.bmp',
  'sim_simb31.bmp',
  'sim_simb32.bmp',
  'sim_simb33.bmp',
  'sim_simb34.bmp',
  'sim_simb35.bmp',
  'sim_simb36.bmp',
  'sim_simb4.bmp',
  'sim_simb5.bmp',
  'sim_simb6.bmp',
  'sim_simb7.bmp',
  'sim_simb8.bmp',
  'sim_simb8_40.bmp',
  'sim_simb9.bmp',
  'sim_ulec.bmp',
];

export function getSimboloGraficoEditorBaseLibrary() {
  return SIMBOLO_GRAFICO_EDITOR_BASE_LIBRARY.map((fileName, index) => {
    const code = fileName.replace(/\.bmp$/i, '');
    return {
      id: code,
      code,
      fileName,
      order: index + 1,
      imageUrl: `/app/assets/Icones/${fileName}`,
      imageAlt: `Símbolo-base ${code}`,
      sourceType: 'biblioteca-base',
    };
  });
}
